services:
  - type: web
    name: compilemate
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn compilemate.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: compilemate-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: compilemate-db
    databaseName: compilemate_db
    user: compilemate_user

